name: Node CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: sudo npm i -g typescript@3.9.4
      - run: node --version
      - run: tsc --version
      - name: Compile
        run: |
          time tsc **/*.ts --lib es6,es2016,es2017,es2018,esnext --target es2018 --module commonjs --outDir dist
